create table events (
    id number generated always as identity primary key,
    name varchar2(100) not null,
    total_seats number default 0 not null 
);

create table seats(
    id number  generated always as identity primary key,
    event_id number not null,
    seat_number number not null,
    status number default 0,
    version number default 0,
    CONSTRAINT fk_event FOREIGN KEY (event_id) REFERENCES events(id)
);

create table bookings(
    id number  generated always as identity primary key,
    event_id number not null,
    seat_id number not null,
    user_email varchar2(100),
    booking_time timestamp default current_timestamp,
    CONSTRAINT fk_booking_seat FOREIGN KEY (seat_id) REFERENCES seats(id)
);

CREATE TABLE users (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR2(100),
    email VARCHAR2(100) UNIQUE,
    password VARCHAR2(255), 
    balance NUMBER DEFAULT 0
);
drop table bookings;
create table orders(
    id number  generated always as identity primary key,
    event_id number not null,
    user_email varchar2(100),
    status varchar2(50),
    booking_time timestamp default current_timestamp
);
create table order_items(
    id number  generated always as identity primary key,
    order_id number not null,
    seat_id number not null,
    constraint fk_order_id FOREIGN Key(order_id) REFERENCES orders(id),
    CONSTRAINT fk_booking_seat FOREIGN KEY (seat_id) REFERENCES seats(id)
)
create table outbox_events(
    id number generated always as identity primary key,
    payload varchar2(4000) not null,
    status varchar2(20) default 'PENDING',
    created_at timestamp default current_timestamp
);
